name: Docker Image CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
  build:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - run: echo "/opt/conda/bin:${PATH}" >> $GITHUB_PATH
    - run: sudo apt-get -y update && sudo apt-get -y install wget gcc && wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b -f -p /opt/conda && export PATH=/opt/conda/bin:$PATH && conda update -y conda && conda install -y conda-build && conda update -y conda-build 
    - run: conda install -c anaconda python=3.8
    - run: conda install -c dhealth -c bioconda -c conda-forge pyecvl-cpu
    - run: export PATH=/opt/conda/bin:$PATH && pip install pytest wheel
    - shell: bash
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: echo "$DOCKER_REPO" > docker/repo.txt
    - run: export PATH=/opt/conda/bin:$PATH && make docker-push


