name: Docker Image CI

# on:
#   push:
#     branches: [ $default-branch feat/github-actions ]
#   pull_request:
#     branches: [ $default-branch ]
on: [push]
jobs:

  build:

    runs-on: ubuntu-latest
    env:
      PATH: "/opt/conda/bin:${PATH}"


    steps:
    - uses: actions/checkout@v2
    - run: echo "/opt/conda/bin:${PATH}" >> $GITHUB_PATH
    - run: apt-get -y update && apt-get -y install wget gcc &&     wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh &&     bash Miniconda3-latest-Linux-x86_64.sh -b -f -p /opt/conda &&     conda update -y conda &&     conda install -y conda-build &&     conda update -y conda-build
      conda install -c dhealth -c bioconda -c conda-forge pyecvl-cpu
    - run:  pip install pytest wheel
    - run: pip install -e .
    - run: make docker


