name: Docker Image CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      id: tag-creation
      uses: anothrNick/github-tag-action@1.34.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        RELEASE_BRANCHES: master,develop

    outputs:
      new_tag: ${{ steps.tag-creation.outputs.new_tag }}
  build:
    runs-on: ubuntu-latest
    needs: bump-version
    container: dhealth/pylibs-toolkit:0.10.1-gpu
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - shell: bash
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: echo "$DOCKER_REPO" > docker/repo.txt
    - run: echo  "${{ needs.bump-version.outputs.new_tag }}" > VERSION
    - run: make docker-push


