name: Docker Image CI

# on:
#   push:
#     branches: [ $default-branch feat/github-actions ]
#   pull_request:
#     branches: [ $default-branch ]
on: [push]
jobs:

  build:

    runs-on: dhealth/pylibs-toolkit:0.10.1-gpu

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make docker
