name: Docker Image CI

# on:
#   push:
#     branches: [ $default-branch feat/github-actions ]
#   pull_request:
#     branches: [ $default-branch ]
on: [push]
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: echo "/opt/conda/bin:${PATH}" >> $GITHUB_PATH
    - run: sudo apt-get -y update && sudo apt-get -y install wget gcc && wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b -f -p /opt/conda && export PATH=/opt/conda/bin:$PATH && conda update -y conda && conda install -y conda-build && conda update -y conda-build 
    - run: conda install -c anaconda python=3.8
    - run: conda install -c dhealth -c bioconda -c conda-forge pyecvl-cpu
    - run: export PATH=/opt/conda/bin:$PATH && pip install pytest wheel
    - run: export PATH=/opt/conda/bin:$PATH && pip install -e .
    - run: export PATH=/opt/conda/bin:$PATH && sudo -E make docker


