name: Docker Image CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - run: echo "/opt/conda/bin:${PATH}" >> $GITHUB_PATH
    - run: sudo apt-get -y update && sudo apt-get -y install wget gcc && wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b -f -p /opt/conda && export PATH=/opt/conda/bin:$PATH && conda update -y conda && conda install -y conda-build && conda update -y conda-build 
    - run: conda install -c anaconda python=3.8
    - run: conda install -c dhealth -c bioconda -c conda-forge pyecvl-cpu
    - run: export PATH=/opt/conda/bin:$PATH && pip install pytest wheel
    - run: echo "mdrio" > docker/repo.txt
    - run: export PATH=/opt/conda/bin:$PATH && make docker-push


