name: Docker Image CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
    - run: conda install -c dhealth -c bioconda -c conda-forge pyecvl-cpu
    - run:  pip install pytest wheel

    - name: test
      run: make test

    - name: Bump version and push tag
      id: tag-creation
      uses: anothrNick/github-tag-action@1.34.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        RELEASE_BRANCHES: master

    - name: update VERSION file
      run: echo  "${{ steps.tag-creation.outputs.new_tag }}" > VERSION

    - name: set docker repo
      shell: bash
      env:
        DOCKER_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}
      run: echo "$DOCKER_REPO" > docker/repo.txt

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: build and push docker images
      run: make docker-push skip_test=true


